version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:2.14.2-pg15
    container_name: auragrid-db
    environment:
      - POSTGRES_USER=bescom_admin
      - POSTGRES_PASSWORD=grid_secure_pass
      - POSTGRES_DB=auragrid
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: auragrid-zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: auragrid-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

  ai-engine:
    build: ./ai-engine
    container_name: auragrid-ai-engine
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://bescom_admin:grid_secure_pass@auragrid-db:5432/auragrid
    volumes:
      # SPEED HACK: Sync your local 'ai-engine' and 'data' folder
      - ./ai-engine:/app
      - ./data:/app/data
    depends_on:
      - timescaledb

  core-api:
    build: ./core-api
    container_name: auragrid-core
    ports:
      - "8080:8080"
    environment:
      - KAFKA_BROKERS=kafka:9092
      - DB_URL=postgres://bescom_admin:grid_secure_pass@timescaledb:5432/auragrid
      - AI_ENGINE_URL=http://ai-engine:8000
    volumes:
      # SPEED HACK: Sync local Go code for hot-reloading
      - ./core-api:/app
    depends_on:
      - kafka
      - timescaledb

  frontend:
    build: ./frontend
    container_name: auragrid-ui
    ports:
      - "3000:3000"
    volumes:
      # SPEED HACK: Sync local React code
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - core-api